name: Codojo CI

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]  

jobs:
#Este job analiza si hay un error de sintaxis en el codigo y sus vulnerabilidades (Linter).

  sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Check code
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 

  build:
      if: ${{ github.event_name == 'push' }}
      strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout main branch from GitHub 
          uses: actions/checkout@v3
        - name: Set up JAVA
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: 8
        - name: Have GitHub Actions Build Maven Project
          run: |
            mvn -B package --file pom.xml
            mkdir staging && cp target/*.jar staging
        - name: Persist workflow data as artificats
          uses: actions/upload-artifact@v3
          with:
            name: CodojoApp
            path: staging
        - name: Upload file properties
          uses: actions/upload-artifact@v2
          with:
            name: Fileproperties
            path: src/AddAppToCodojoConfig.config.properties
  
  slack_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack pull request open
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SLACK_WEBHOOK_URL : ${{secrets.SLACK_PULL_REQUEST_WEBHOOK}}
        PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
        PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
        PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
        PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }}
        PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
        PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
        PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
        PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }}
        PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
        PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }}
        IS_SEND_HERE_MENTION : false
        MAKE_PRETTY : true
        MAKE_COMPACT : true
        IS_PR_FROM_FORK: false
      uses: jun3453/slack-pr-open-notification-action@v1.3.0

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch from GitHub 
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - uses: actions/download-artifact@v3
        with:
          name: CodojoApp
          path: staging
      - uses: actions/download-artifact@v3
        with:
           name: Fileproperties
           path: staging
      - name: Deploy to S3 Bucket
        if: ${{ github.event_name == 'push' }}
        run: aws s3 sync --delete staging s3://appcodojo
    
  activate-workflow:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Codojoio
          repo: UiLogin
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow_file_name: download.yml
          ref: main
